ability = {'Overgrow','Overgrow',
'Overgrow','Overgrow',
'Chlorophyll','Chlorophyll',
'Blaze','Blaze',
'Blaze','Blaze',
'Blaze','Blaze',
'Torrent','Torrent',
'Torrent','Torrent',
'Torrent','Torrent',
'Shield Dust','Shield Dust',
'Shed Skin','Shed Skin',
'Compoundeyes','Compoundeyes',
'Shield Dust','Shield Dust',
'Shed Skin','Shed Skin',
'Swarm','Swarm',
'Keen Eye','Keen Eye',
'Keen Eye','Keen Eye',
'Early Bird','Early Bird',
'Run Away','Run Away',
'Guts','Guts',
'Keen Eye','Keen Eye',
'Early Bird','Early Bird',
'Intimidate','Intimidate',
'Intimidate','Intimidate',
'Lightningrod','Lightningrod',
'Lightningrod','Lightningrod',
'Rough Skin','Rough Skin',
'Rough Skin','Rough Skin',
'Poison Point','Poison Point',
'Poison Point','Poison Point',
'Poison Point','Poison Point',
'Poison Point','Poison Point',
'Poison Point','Poison Point',
'Poison Point','Poison Point',
'Cute Charm','Cute Charm',
'Cute Charm','Cute Charm',
'Pressure','Pressure',
'Pressure','Pressure',
'Cute Charm','Cute Charm',
'Cute Charm','Cute Charm',
'Inner Focus','Inner Focus',
'Inner Focus','Inner Focus',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Effect Spore','Effect Spore',
'Effect Spore','Effect Spore',
'Shield Dust','Shield Dust',
'Shield Dust','Shield Dust',
'Arena Trap','Arena Trap',
'Arena Trap','Arena Trap',
'Limber','Limber',
'Limber','Limber',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Vital Spirit','Vital Spirit',
'Vital Spirit','Vital Spirit',
'Intimidate','Intimidate',
'Intimidate','Blaze',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Synchronize','Synchronize',
'Synchronize','Synchronize',
'Synchronize','Synchronize',
'Guts','Guts',
'Guts','Guts',
'Guts','Guts',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Clear Body','Liquid Ooze',
'Clear Body','Liquid Ooze',
'Rock Head','Rock Head',
'Rock Head','Rock Head',
'Rock Head','Rock Head',
'Flame Body','Flame Body',
'Flame Body','Flame Body',
'Oblivious','Own Tempo',
'Shell Armor','Shell Armor',
'Magnet Pull','Magnet Pull',
'Magnet Pull','Magnet Pull',
'Keen Eye','Inner Focus',
'Early Bird','Run Away',
'Early Bird','Run Away',
'Thick Fat','Thick Fat',
'Swift Swim','Thick Fat',
'Poison Point','Poison Point',
'Poison Point','Poison Point',
'Shell Armor','Shell Armor',
'Shell Armor','Shell Armor',
'Levitate','Levitate',
'Levitate','Levitate',
'Levitate','Levitate',
'Rock Head','Rock Head',
'Insomnia','Insomnia',
'Insomnia','Insomnia',
'Shell Armor','Shell Armor',
'Shell Armor','Shell Armor',
'Static','Static',
'Static','Static',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Lightningrod','Lightningrod',
'Lightningrod','Lightningrod',
'Limber','Limber',
'Guts','Guts',
'Thick Fat','Thick Fat',
'Levitate','Levitate',
'Levitate','Levitate',
'Lightningrod','Lightningrod',
'Lightningrod','Lightningrod',
'Natural Cure','Serene Grace',
'Chlorophyll','Chlorophyll',
'Early Bird','Early Bird',
'Swift Swim','Swift Swim',
'Poison Point','Poison Point',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Natural Cure','Natural Cure',
'Natural Cure','Natural Cure',
'Synchronize','Synchronize',
'Swarm','Swarm',
'Inner Focus','Inner Focus',
'Static','Static',
'Flame Body','Flame Body',
'Intimidate','Intimidate',
'Intimidate','Intimidate',
'Swift Swim','Swift Swim',
'Intimidate','Intimidate',
'Shell Armor','Shell Armor',
'Shadow Tag','Shadow Tag',
'Run Away','Run Away',
'Swift Swim','Swift Swim',
'Static','Static',
'Guts','Guts',
'Trace','Trace',
'Shell Armor','Shell Armor',
'Shell Armor','Shell Armor',
'Battle Armor','Battle Armor',
'Battle Armor','Battle Armor',
'Rock Head','Rock Head',
'Guts','Thick Fat',
'Pressure','Pressure',
'Pressure','Pressure',
'Pressure','Pressure',
'Shed Skin','Shed Skin',
'Shed Skin','Shed Skin',
'Thick Fat','Thick Fat',
'Pressure','Run Away',
'Synchronize','Synchronize',
'Overgrow','Overgrow',
'Overgrow','Overgrow',
'Thick Fat','Thick Fat',
'Blaze','Blaze',
'Blaze','Blaze',
'Blaze','Blaze',
'Torrent','Torrent',
'Torrent','Torrent',
'Battle Armor','Battle Armor',
'Early Bird','Keen Eye',
'Early Bird','Keen Eye',
'Insomnia','Insomnia',
'Insomnia','Insomnia',
'Swarm','Swarm',
'Swarm','Swarm',
'Swarm','Swarm',
'Swarm','Swarm',
'Inner Focus','Inner Focus',
'Volt Absorb','Volt Absorb',
'Volt Absorb','Volt Absorb',
'Static','Static',
'Cute Charm','Cute Charm',
'Cute Charm','Cute Charm',
'Serene Grace','Serene Grace',
'Serene Grace','Serene Grace',
'Synchronize','Synchronize',
'Synchronize','Synchronize',
'Static','Static',
'Static','Static',
'Static','Static',
'Chlorophyll','Chlorophyll',
'Huge Power','Huge Power',
'Huge Power','Huge Power',
'Rock Head','Rock Head',
'Swift Swim','Swift Swim',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Vital Spirit','Vital Spirit',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Speed Boost','Speed Boost',
'Water Absorb','Water Absorb',
'Water Absorb','Water Absorb',
'Synchronize','Synchronize',
'Synchronize','Synchronize',
'Insomnia','Insomnia',
'Natural Cure','Natural Cure',
'Levitate','Levitate',
'Levitate','Levitate',
'Shadow Tag','Shadow Tag',
'Inner Focus','Inner Focus',
'Rough Skin','Rough Skin',
'Shell Armor','Shell Armor',
'Serene Grace','Serene Grace',
'Hyper Cutter','Hyper Cutter',
'Rock Head','Rock Head',
'Intimidate','Intimidate',
'Intimidate','Intimidate',
'Swift Swim','Swift Swim',
'Swarm','Swarm',
'Shell Armor','Shell Armor',
'Guts','Guts',
'Inner Focus','Inner Focus',
'Guts','Guts',
'Guts','Guts',
'Flame Body','Flame Body',
'Flame Body','Flame Body',
'Oblivious','Oblivious',
'Thick Fat','Thick Fat',
'Natural Cure','Natural Cure',
'Hustle','Hustle',
'Suction Cups','Suction Cups',
'Vital Spirit','Vital Spirit',
'Swift Swim','Swift Swim',
'Keen Eye','Keen Eye',
'Early Bird','Early Bird',
'Intimidate','Intimidate',
'Swift Swim','Swift Swim',
'Cute Charm','Cute Charm',
'Battle Armor','Battle Armor',
'Trace','Trace',
'Intimidate','Intimidate',
'Own Tempo','Own Tempo',
'Guts','Guts',
'Intimidate','Intimidate',
'Oblivious','Oblivious',
'Static','Static',
'Flame Body','Flame Body',
'Thick Fat','Thick Fat',
'Natural Cure','Serene Grace',
'Lightningrod','Pressure',
'Serene Grace','Pressure',
'Battle Armor','Pressure',
'Guts','Guts',
'Shed Skin','Shed Skin',
'Battle Armor','Battle Armor',
'Pressure','Run Away',
'Pressure','Run Away',
'Natural Cure','Natural Cure',
' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',
'Overgrow','Overgrow',
'Overgrow','Overgrow',
'Overgrow','Overgrow',
'Speed Boost','Blaze',
'Blaze','Blaze',
'Blaze','Blaze',
'Torrent','Torrent',
'Torrent','Torrent',
'Swift Swim','Torrent',
'Run Away','Run Away',
'Intimidate','Intimidate',
'Guts','Guts',
'Guts','Guts',
'Shield Dust','Shield Dust',
'Shed Skin','Shed Skin',
'Swarm','Swarm',
'Shed Skin','Shed Skin',
'Shield Dust','Shield Dust',
'Swift Swim','Rain Dish',
'Swift Swim','Rain Dish',
'Swift Swim','Swift Swim',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Chlorophyll','Chlorophyll',
'Compoundeyes','Compoundeyes',
'Speed Boost','Speed Boost',
'Wonder Guard','Wonder Guard',
'Guts','Guts',
'Guts','Guts',
'Effect Spore','Effect Spore',
'Effect Spore','Effect Spore',
'Inner Focus','Inner Focus',
'Keen Eye','Keen Eye',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Intimidate','Intimidate',
'Pressure','Pressure',
'Pressure','Pressure',
'Cute Charm','Cute Charm',
'Cute Charm','Cute Charm',
'Color Change','Color Change',
'Levitate','Levitate',
'Levitate','Levitate',
'Battle Armor','Battle Armor',
'Shell Armor','Shell Armor',
'Pressure','Pressure',
'Oblivious','Oblivious',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Shell Armor','Shell Armor',
'Shell Armor','Shell Armor',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Rough Skin','Rough Skin',
'Rough Skin','Rough Skin',
'Arena Trap','Arena Trap',
'Levitate','Levitate',
'Levitate','Levitate',
'Thick Fat','Guts',
'Thick Fat','Guts',
'Static','Static',
'Intimidate','Intimidate',
'Oblivious','Oblivious',
'Magma Armor','Magma Armor',
'Thick Fat','Thick Fat',
'Thick Fat','Thick Fat',
'Rain Dish','Rain Dish',
'Sand Veil','Sand Veil',
'Chlorophyll','Chlorophyll',
'Inner Focus','Inner Focus',
'Intimidate','Intimidate',
'Levitate','Levitate',
'Levitate','Levitate',
'Huge Power','Huge Power',
'Thick Fat','Thick Fat',
'Thick Fat','Thick Fat',
'Plus','Plus',
'Minus','Minus',
'Intimidate','Intimidate',
'Pure Power','Pure Power',
'Pure Power','Pure Power',
'Natural Cure','Natural Cure',
'Natural Cure','Natural Cure',
'Shadow Tag','Shadow Tag',
'Levitate','Levitate',
'Keen Eye','Keen Eye',
'Natural Cure','Natural Cure',
'Truant','Truant',
'Vital Spirit','Vital Spirit',
'Truant','Truant',
'Liquid Ooze','Liquid Ooze',
'Liquid Ooze','Liquid Ooze',
'Chlorophyll','Chlorophyll',
'Vital Spirit','Vital Spirit',
'Vital Spirit','Vital Spirit',
'Vital Spirit','Vital Spirit',
'Shell Armor','Shell Armor',
'Swift Swim','Swift Swim',
'Swift Swim','Swift Swim',
'Pressure','Pressure',
'Insomnia','Insomnia',
'Insomnia','Insomnia',
'Shed Skin','Shed Skin',
'Guts','Guts',
'Swift Swim','Swift Swim',
'Rock Head','Rock Head',
'Rock Head','Rock Head',
'Rock Head','Rock Head',
'Forecast','Forecast',
'Swarm','Swarm',
'Oblivious','Oblivious',
'Suction Cups','Suction Cups',
'Suction Cups','Suction Cups',
'Battle Armor','Battle Armor',
'Battle Armor','Battle Armor',
'Synchronize','Synchronize',
'Synchronize','Synchronize',
'Trace','Trace',
'Rock Head','Rock Head',
'Rock Head','Rock Head',
'Intimidate','Intimidate',
'Battle Armor','Battle Armor',
'Battle Armor','Battle Armor',
'Battle Armor','Battle Armor',
'Clear Body','Clear Body',
'Clear Body','Clear Body',
'Clear Body','Clear Body',
'Torrent','Run Away',
'Rock Head','Run Away',
'Intimidate','Run Away',
'Levitate','Levitate',
'Levitate','Levitate',
'Serene Grace','Serene Grace',
'Pressure','Pressure',
'Levitate','Levitate',}
